import { defineConfig } from "tsup";

export default defineConfig({
  clean: true,
  dts: true,
  entry: {
    index: "src/index.ts",
    "components/index": "src/components/index.ts",
    "components/AnimatedButton/index": "src/components/AnimatedButton/index.ts",
    "components/AnimatedCard/index": "src/components/AnimatedCard/index.ts",
    "components/Alert/index": "src/components/Alert/index.ts",
    "components/AuraTrail/index": "src/components/AuraTrail/index.ts",
    "components/AxisCarousel3D/index": "src/components/AxisCarousel3D/index.ts",
    "components/Avatar/index": "src/components/Avatar/index.ts",
    "components/AvatarStack/index": "src/components/AvatarStack/index.ts",
    "components/AvatarTooltip/index": "src/components/AvatarTooltip/index.ts",
    "components/Badge/index": "src/components/Badge/index.ts",
    "components/BreathingText/index": "src/components/BreathingText/index.ts",
    "components/BlurFadeIn/index": "src/components/BlurFadeIn/index.ts",
    "components/FadeInText/index": "src/components/FadeInText/index.ts",
    "components/Loader/index": "src/components/Loader/index.ts",
    "components/Reveal/index": "src/components/Reveal/index.ts",
    "components/SlideIn/index": "src/components/SlideIn/index.ts",
    "components/TextRotate/index": "src/components/TextRotate/index.ts",
    "components/Tooltip/index": "src/components/Tooltip/index.ts",
    "components/TypewriterText/index": "src/components/TypewriterText/index.ts",
    "internal/fadein": "src/internal/fadein.ts",
    "internal/guards": "src/internal/guards.ts",
    "internal/slidein": "src/internal/slidein.ts",
    "internal/textrotate": "src/internal/textrotate.ts",
  },
  external: ["astro", /\.astro$/],
  format: ["esm"],
  outDir: "dist",
  onSuccess: "node ./scripts/copy-astro-files.mjs",
  sourcemap: true,
  splitting: false,
  target: "es2021",
  treeshake: true,
});
