import { defineConfig } from "tsup";

export default defineConfig({
  clean: true,
  dts: true,
  entry: {
    index: "src/index.ts",
    "components/index": "src/components/index.ts",
    "components/AnimatedButton/index": "src/components/AnimatedButton/index.ts",
    "components/AnimatedCard/index": "src/components/AnimatedCard/index.ts",
    "components/ExpandableCard/index": "src/components/ExpandableCard/index.ts",
    "components/FadeInText/index": "src/components/FadeInText/index.ts",
    "components/GlassCard/index": "src/components/GlassCard/index.ts",
    "components/Loader/index": "src/components/Loader/index.ts",
    "components/ProgressBar/index": "src/components/ProgressBar/index.ts",
    "components/ScaleIn/index": "src/components/ScaleIn/index.ts",
    "components/Tooltip/index": "src/components/Tooltip/index.ts",
    "components/TypewriterText/index": "src/components/TypewriterText/index.ts",
    "internal/fadein": "src/internal/fadein.ts",
    "internal/guards": "src/internal/guards.ts",
  },
  external: ["astro", /\.astro$/],
  format: ["esm"],
  outDir: "dist",
  onSuccess: "node ./scripts/copy-astro-files.mjs",
  sourcemap: true,
  splitting: false,
  target: "es2021",
  treeshake: true,
});
